// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NurseShifts.Data;

#nullable disable

namespace NurseShifts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251226134615_AddManualAssignmentFlag")]
    partial class AddManualAssignmentFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("NurseShifts.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoAssignHeadNurseMorning")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadNurseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeadNurseId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("NurseShifts.Models.CompensatoryTimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursCompensated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.ToTable("CompensatoryTimeOffs");
                });

            modelBuilder.Entity("NurseShifts.Models.Nurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvoidedShifts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanHandleResponsibility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractedHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPoolNurse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxConsecutiveWorkDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxOvertimeHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinRestHoursBetweenShifts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredShifts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrefersConsecutiveDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryClinicId");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("NurseShifts.Models.NurseClinicAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanBeBorrowed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("NurseId", "ClinicId")
                        .IsUnique();

                    b.ToTable("NurseClinicAssignments");
                });

            modelBuilder.Entity("NurseShifts.Models.NurseLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.ToTable("NurseLeaves");
                });

            modelBuilder.Entity("NurseShifts.Models.NurseShiftWish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WishType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.ToTable("NurseShiftWishes");
                });

            modelBuilder.Entity("NurseShifts.Models.OvertimeBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompensatoryHoursUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractedHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NurseId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("OvertimeBalances");
                });

            modelBuilder.Entity("NurseShifts.Models.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualAssignment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResponsibleNurse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("NurseId");

                    b.HasIndex("Date", "ShiftType", "NurseId")
                        .IsUnique();

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("NurseShifts.Models.ShiftConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredNurses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredSeniorNurses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresResponsibleNurse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftDurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId", "ShiftType", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("ShiftConfigurations");
                });

            modelBuilder.Entity("NurseShifts.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultContractedHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMaxConsecutiveWorkDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMaxOvertimeHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMinRestHoursBetweenShifts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminPasswordHash = "$2a$11$.lea7HLBOb5xwftzvm8hXOriVBT1cJSBln266PVSU7UCbsHpLQ3QS",
                            AdminUsername = "admin",
                            DefaultContractedHoursPerWeek = 40,
                            DefaultMaxConsecutiveWorkDays = 5,
                            DefaultMaxOvertimeHoursPerWeek = 8,
                            DefaultMinRestHoursBetweenShifts = 11,
                            Language = "en"
                        });
                });

            modelBuilder.Entity("NurseShifts.Models.Clinic", b =>
                {
                    b.HasOne("NurseShifts.Models.Nurse", "HeadNurse")
                        .WithMany()
                        .HasForeignKey("HeadNurseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadNurse");
                });

            modelBuilder.Entity("NurseShifts.Models.CompensatoryTimeOff", b =>
                {
                    b.HasOne("NurseShifts.Models.Nurse", "Nurse")
                        .WithMany("CompensatoryTimeOffs")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NurseShifts.Models.Nurse", b =>
                {
                    b.HasOne("NurseShifts.Models.Clinic", "PrimaryClinic")
                        .WithMany("Nurses")
                        .HasForeignKey("PrimaryClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryClinic");
                });

            modelBuilder.Entity("NurseShifts.Models.NurseClinicAssignment", b =>
                {
                    b.HasOne("NurseShifts.Models.Clinic", "Clinic")
                        .WithMany("BorrowableNurses")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NurseShifts.Models.Nurse", "Nurse")
                        .WithMany("ClinicAssignments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NurseShifts.Models.NurseLeave", b =>
                {
                    b.HasOne("NurseShifts.Models.Nurse", "Nurse")
                        .WithMany("Leaves")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NurseShifts.Models.NurseShiftWish", b =>
                {
                    b.HasOne("NurseShifts.Models.Nurse", "Nurse")
                        .WithMany("ShiftWishes")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NurseShifts.Models.OvertimeBalance", b =>
                {
                    b.HasOne("NurseShifts.Models.Nurse", "Nurse")
                        .WithMany("OvertimeBalances")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NurseShifts.Models.ShiftAssignment", b =>
                {
                    b.HasOne("NurseShifts.Models.Clinic", "Clinic")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NurseShifts.Models.Nurse", "Nurse")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NurseShifts.Models.ShiftConfiguration", b =>
                {
                    b.HasOne("NurseShifts.Models.Clinic", "Clinic")
                        .WithMany("ShiftConfigurations")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("NurseShifts.Models.Clinic", b =>
                {
                    b.Navigation("BorrowableNurses");

                    b.Navigation("Nurses");

                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftConfigurations");
                });

            modelBuilder.Entity("NurseShifts.Models.Nurse", b =>
                {
                    b.Navigation("ClinicAssignments");

                    b.Navigation("CompensatoryTimeOffs");

                    b.Navigation("Leaves");

                    b.Navigation("OvertimeBalances");

                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftWishes");
                });
#pragma warning restore 612, 618
        }
    }
}
